workflows:
  flutter-android-apk:
    name: QuickHelper Android APK Build
    
    environment:
      # Flutter environment setup
      flutter: stable 
      
    scripts:
      - name: Get Dependencies
        # pubspec.yaml se saari libraries download karega
        script: |
          flutter pub get
          
      - name: Build Android Release APK
        # Flutter ka main command APK file banane ke liye
        script: |
          flutter build apk --release
          
    artifacts:
      # Is path par aapki APK file banegi
      - build/app/outputs/flutter-apk/app-release.apk
    
    # Simple email notification (agar aapne Codemagic settings mein email set kiya hai)
    publishing:
      email:
        triggering:
          - success
          - failure
